name: Rust

on:
  push:
    branches: [ master, testing ]
  pull_request:
    branches: [ master, testing ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - name: wasm-pack-action
      # You may pin to the exact commit or the version.
      # uses: jetli/wasm-pack-action@f98777369a49686b132a9e8f0fdd59837bf3c3fd
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install (eg. "v0.9.1", "latest")
        version: latest # optional, default is latest
    - name: Build
      run: wasm-pack build --release --target=no-modules
    - name: Create zipped extension
      run:    mkdir wasm/ &&
              mv -R "pkg/rrefresh_bg.wasm" wasm/ &&
              mv -R "pkg/rrefresh.js" wasm/ &&
              mkdir rrefresh/ &&
              mv -R wasm/ rrefresh/ &&
              mv -R js/ rrefresh/ &&
              mv -R html/*.html rrefresh/ &&
              mv -R html/*.js rrefresh/ &&
              mv -R html/*.css rrefresh/ &&
              mv -R icon/ rrefresh/ &&
              mv manifest.json rrefresh/
    - name: Create package artifact
      uses: actions/upload-artifact@v2
      with:
          name: rrefresh
          path: rrefresh
